### ISSUE TITLE
Expected Download / Sync Speed

### ISSUE THREAD

**Issue by memoriesadrift** [fluxprotocol/flux-capacitor#2]
Hi,
I've been trying to get flux-capactor to track contracts on the NEAR betanet (including the NEAR EVM). I've managed to get flux-capacitor up and running with the instructions provided, however it seems to get stuck on downloading headers, around 0.5% for me, with a different percentage for a colleague trying the same. We've both left it running for a couple of hours with no real progress. [Here](https://pastebin.com/2DNtM3un) are my logs for reference. The program never hangs, it's just difficult to draw any meaningful conclusions from its current behaviour.

**Reproduction steps:**
1. Clone repo, run mongo `git clone git@github.com:fluxprotocol/flux-capacitor.git`, `cd flux-capacitor`, `docker-compose up`
2. run `cargo run --release -- --home-dir ~/.near/betanet init --chain-id betanet --download`
3. replace `config.json` with the [file provided by NEAR](https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/betanet/config.json) (found in the nearcore/indexer repo [here](https://github.com/near/nearcore/tree/master/chain/indexer#testnet--betanet))
4. run `cargo run --release -- --home-dir ~/.near/betanet run`
5. open  `http://localhost:3000/config/add_account?token=ABC123&account_id=evm` -> resulted in success message, registered by flux-capacitor upon relaunch.

I've got a couple of questions, but the main ones relating to this issue:
What is the expected time to download headers? 
Am I missing something in my project setup?
Where is this data stored? How can it be queried or viewed? 
You've mentioned that flux-capacitor requires " a specific tx log encoded in json in order [...] to pickup your log and insert it into the database", where should this be encoded/provided? 
Thanks a lot in advance!

**Comment by jasperdg** [comment]
Hey awesome that you're getting setup. It can take hours to a day to sync depending on internet speed (we use servers to run our indexers).

First thing im missing in your steps is running the mongodb docker image where logs will be stored. 

CC'ing @FranklinWaller who's the main contributor to this implementation, can you help Samuel with verifying that his steps are correct?

**Comment by FranklinWaller** [comment]
Hi, It looks like your setup is okay. It could be that the beta net is not very stable in terms of outage (because of either updates or something else). We can't really offer support for syncing as that is mostly https://github.com/near/nearcore/tree/master/chain/indexer doing the work. We are just wrapping and listening to it.

The data is store in your MongoDB database you can use Robo 3T to view the data that's stored inside your database. (Using the credentials from your .env file). 

You can use the env::log from the near_sdk to log entries. For example: 

```
pub fn log_pool(pool: &Pool) {
	env::log(
		json!({
                        "type": "pools".to_string(),
                        "action": "update",
                        "cap_id": format!("p_{}", pool.id),
	                "params": {
                              "id": U64(pool.id),
                              "outcomes": pool.outcomes,
                              "swap_fee": U128(pool.swap_fee),
                              "collateral_token_id": pool.collateral_token_id,
                              "total_withdrawn_fees": U128(pool.total_withdrawn_fees),
                              "fee_pool_weight": U128(pool.fee_pool_weight),
                              "block_height": U64(env::block_index()),
	                }
		})
		.to_string()
		.as_bytes()
	);
}
```

You can find more examples here: https://github.com/fluxprotocol/amm/blob/develop/flux/src/logger.rs

**Comment by memoriesadrift** [comment]
Thank you for your answers and quick responses, I appreciate it! If I understand everything correctly, contract code has to be modified to support logging, which isn't something the project I'm working on is keep on doing, so I'll have to look to possibly creating my own wrapper over the near indexer framework. Thank you once again for the quick replies!
